AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys a LaunchTemplate and an AutoScalingGroup.
Parameters:
  ENVname:
    Description: "Server Environment name."
    ConstraintDescription: "Choose an Environment from the drop down"
    Type: "String"
    AllowedValues: 
      - "dev"
      - "prod"

  RegionAmiId:
    Description: Reference to the Region AMI.
    Type: String
    
  InstanceType:
    Description: Amazon EC2 instance type for the instances
    Type: String
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium
    Default: t3.micro

  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: A list of subnets for the Auto Scaling group.

  AppKeyName:
    Type: "String"
    Description: Enter an existing EC2 Key Pair.
    Default: myKP

  WebAppSG:
    Description: Security Group for Web App Instance.
    Type: AWS::EC2::SecurityGroup::Id

  AsgMin:
    Description: A reference to the MinSize.
    Type: String

  AsgDes:
    Description: A reference to the DesiredCapacity.
    Type: String

  AsgMax:
    Description: A reference to the MaxSize.
    Type: String

  WebAppTargetGroup:
    Description: TargetGroup ARN
    Type: String

Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData:
        ImageId:
          Ref: RegionAmiId
        InstanceType:
          Ref: InstanceType
        KeyName:
          Ref: AppKeyName
        SecurityGroupIds:
          - Ref: "WebAppSG"

  AppASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId:
          Ref: myLaunchTemplate
        Version: !GetAtt myLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref WebAppTargetGroup
      MaxSize:
        Ref: AsgMax
      DesiredCapacity:
        Ref: AsgDes
      MinSize:  
        Ref: AsgMin
      VPCZoneIdentifier:
        Ref: Subnets
      Tags:
      - Key: Name
        Value: !Sub "${ENVname}-AppASG"
        PropagateAtLaunch: 'True'

  APPServerScaleUpPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AdjustmentType: "ChangeInCapacity"
      AutoScalingGroupName:
        Ref: "AppASG"
      Cooldown: '300'
      ScalingAdjustment: '1'

  APPServerScaleDownPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AdjustmentType: "ChangeInCapacity"
      AutoScalingGroupName:
        Ref: "AppASG"
      Cooldown: '300'
      ScalingAdjustment: '-1'
      
Outputs:

  AppScalingGroup:
    Description: Auto Scaling Group Reference ID
    Value:
      Ref: AppASG

  APPServerScaleUpPolicy:
    Description: Auto Scaling Up Policy Reference ID
    Value:
      Ref: APPServerScaleUpPolicy

  APPServerScaleDownPolicy:
    Description: Auto Scaling Down Policy Reference ID
    Value:
      Ref: APPServerScaleDownPolicy
      
